version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine  # Alpine версия легче и безопаснее
    container_name: nginx
    restart: unless-stopped
    volumes:
      # Рекомендую использовать относительные пути для переносимости
      - /home/sysops/sites/nginx:/var/www/nginx:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      # Определение сервиса один раз
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      
      # Правила для доменов
      - "traefik.http.routers.playpoy.rule=Host(`playpoy.ru`)"
      - "traefik.http.routers.veselkina.rule=Host(`xn--80adjmjfq2a8l.xn--p1ai`)"
      - "traefik.http.routers.mix-wood.rule=Host(`mix-wood.ru`)"
      - "traefik.http.routers.radionefa.rule=Host(`radionefa.ru`)"
      - "traefik.http.routers.banidlyadushi.rule=Host(`xn--80abkasctn2d8b6d.xn--p1ai`)"
      - "traefik.http.routers.minifun.rule=Host(`minifun.ru`)"
      - "traefik.http.routers.karaoka.rule=Host(`karaoka.ru`)"

      # Общие настройки TLS для всех вышеуказанных роутеров
      # Используем перечисление через запятую для краткости
      - "traefik.http.routers.playpoy.entrypoints=websecure"
      - "traefik.http.routers.playpoy.tls.certresolver=le"
      
      # Повторяем для остальных (Traefik v3 позволяет объединять, 
      # но для надежности оставим явное указание на основной роутер)
      - "traefik.http.routers.veselkina.entrypoints=websecure"
      - "traefik.http.routers.veselkina.tls.certresolver=le"
      - "traefik.http.routers.mix-wood.entrypoints=websecure"
      - "traefik.http.routers.mix-wood.tls.certresolver=le"
      - "traefik.http.routers.radionefa.entrypoints=websecure"
      - "traefik.http.routers.radionefa.tls.certresolver=le"
      - "traefik.http.routers.banidlyadushi.entrypoints=websecure"
      - "traefik.http.routers.banidlyadushi.tls.certresolver=le"
      - "traefik.http.routers.minifun.entrypoints=websecure"
      - "traefik.http.routers.minifun.tls.certresolver=le"
      - "traefik.http.routers.karaoka.entrypoints=websecure"
      - "traefik.http.routers.karaoka.tls.certresolver=le"

networks:
  traefik_proxy:
    external: true