version: '3.8'
services:
  apache:
    image: httpd:2.4-alpine # Alpine версия компактнее
    container_name: apache
    restart: unless-stopped
    # Если вы используете user: "1000:1000", убедитесь, что права на папки логов и сайтов на хосте соответствуют
    user: "1000:1000"
    volumes:
      - /home/sysops/sites/apache/bessonnicza.ru:/var/www/bessonnicza
      - /home/sysops/sites/apache/karaoka.ru:/var/www/karaoka
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - /home/sysops/apache/logs:/usr/local/apache2/logs
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      
      # bessonnicza.ru
      - "traefik.http.routers.bessonnicza.rule=Host(`bessonnicza.ru`)"
      - "traefik.http.routers.bessonnicza.entrypoints=websecure"
      - "traefik.http.routers.bessonnicza.tls.certresolver=le"
      - "traefik.http.routers.bessonnicza.service=apache-svc"
      
      # karaoka.ru (добавим лейбл сразу, так как в конфиге vhost есть)
      - "traefik.http.routers.karaoka-apache.rule=Host(`karaoka.ru`)"
      - "traefik.http.routers.karaoka-apache.entrypoints=websecure"
      - "traefik.http.routers.karaoka-apache.tls.certresolver=le"
      - "traefik.http.routers.karaoka-apache.service=apache-svc"

      - "traefik.http.services.apache-svc.loadbalancer.server.port=80"
    command: ["httpd-foreground"]

networks:
  traefik_proxy:
    external: true